package cloudflare

import (
	"errors"
	"fmt"
	"time"

	"github.com/farseer-go/fs/configure"
	"github.com/farseer-go/fs/snc"
	"github.com/farseer-go/utils/http"
)

// Cloudflare客户端
type Client struct {
	AccountId string // 账户ID
	ApiToken  string // API令牌
}

// 初始化Cloudflare客户端
func New(accountId, apiToken string) *Client {
	return &Client{
		AccountId: accountId,
		ApiToken:  "Bearer " + apiToken,
	}
}

// 初始化Cloudflare客户端
func NewFromConfigure() *Client {
	return &Client{
		AccountId: configure.GetString("cf.account_id"),
		ApiToken:  "Bearer " + configure.GetString("cf.api_token"),
	}
}

// 验证账号ID、令牌是否正确
func (receiver *Client) Verify() (bool, int, error) {
	// curl "https://api.cloudflare.com/client/v4/accounts/$AccountId/tokens/verify" \
	// -H "Authorization: Bearer $ApiToken"

	url := fmt.Sprintf("https://api.cloudflare.com/client/v4/accounts/%s/tokens/verify", receiver.AccountId)
	resultJson, _, _, err := http.RequestProxyConfigure("GET", url, map[string]any{"Authorization": receiver.ApiToken}, nil, "application/json", 2000)

	type AutoGenerated struct {
		Result struct {
			ID     string `json:"id"`
			Status string `json:"status"`
		} `json:"result"`
		Success bool `json:"success"`
		Errors  []struct {
			Code    int    `json:"code"`
			Message string `json:"message"`
		} `json:"errors"`
		Messages []struct {
			Code    int         `json:"code"`
			Message string      `json:"message"`
			Type    interface{} `json:"type"`
		} `json:"messages"`
	}
	var result AutoGenerated
	snc.Unmarshal([]byte(resultJson), &result)

	if len(result.Errors) > 0 {
		return result.Success, result.Errors[0].Code, errors.New(result.Errors[0].Message)
	}

	if len(result.Messages) > 0 {
		return result.Success, result.Messages[0].Code, err
	}

	return result.Success, 0, err
}

type Zones struct {
	Result []struct {
		ID                   string        `json:"id"`                      // 区域ID xxxxxxxxxxxxxxxxxxxxxx
		Name                 string        `json:"name"`                    // 区域名称 example.com
		Status               string        `json:"status"`                  // 区域状态 active
		Paused               bool          `json:"paused"`                  // 是否暂停 false
		Type                 string        `json:"type"`                    // 区域类型 full
		DevelopmentMode      int           `json:"development_mode"`        // 开发模式 0
		NameServers          []string      `json:"name_servers"`            // 名称服务器 [abby.ns.cloudflare.com, ben.ns.cloudflare.com]
		OriginalNameServers  []string      `json:"original_name_servers"`   // 原始名称服务器 [ns1.example.com, ns2.example.com]
		OriginalRegistrar    string        `json:"original_registrar"`      // 原始注册商 GoDaddy.com, LLC
		OriginalDnshost      interface{}   `json:"original_dnshost"`        // 原始DNS主机 nil
		ModifiedOn           time.Time     `json:"modified_on"`             // 修改时间 2020-04-14T12:34:56Z
		CreatedOn            time.Time     `json:"created_on"`              // 创建时间 2020-01-10T08:00:00Z
		ActivatedOn          time.Time     `json:"activated_on"`            // 激活时间 2020-01-15T09:30:00Z
		VanityNameServers    []interface{} `json:"vanity_name_servers"`     // 虚拟名称服务器 []
		VanityNameServersIps interface{}   `json:"vanity_name_servers_ips"` // 虚拟名称服务器IP nil
		Meta                 struct {
			Step                   int  `json:"step"`                     // 步骤 4
			CustomCertificateQuota int  `json:"custom_certificate_quota"` // 自定义证书配额 0
			PageRuleQuota          int  `json:"page_rule_quota"`          // 页面规则配额 3
			PhishingDetected       bool `json:"phishing_detected"`        // 是否检测到网络钓鱼 false
		} `json:"meta"`
		Owner struct {
			ID    interface{} `json:"id"`    // 所有者ID nil
			Type  string      `json:"type"`  // 所有者类型 user
			Email interface{} `json:"email"` // 所有者邮箱 nil
		} `json:"owner"`
		Account struct {
			ID   string `json:"id"`   // 账户ID xxxxxxxxxxxxxxxxxxxxxx
			Name string `json:"name"` // 账户名称 Example Account
		} `json:"account"`
		Tenant struct {
			ID   interface{} `json:"id"`   // 租户ID nil
			Name interface{} `json:"name"` // 租户名称 nil
		} `json:"tenant"`
		TenantUnit struct {
			ID interface{} `json:"id"` // 租户单元ID nil
		} `json:"tenant_unit"`
		Permissions []string `json:"permissions"` // 权限 ["#zone:read", "#zone:edit", "#dns_records:edit"]
		Plan        struct {
			ID                string `json:"id"`                 // 计划ID xxxxxxxxxxxxxxxxxxxxxx
			Name              string `json:"name"`               // 计划名称 Free Website
			Price             int    `json:"price"`              // 计划价格 0
			Currency          string `json:"currency"`           // 计划货币 USD
			Frequency         string `json:"frequency"`          // 计划频率 monthly
			IsSubscribed      bool   `json:"is_subscribed"`      // 是否已订阅 false
			CanSubscribe      bool   `json:"can_subscribe"`      // 是否可以订阅 true
			LegacyID          string `json:"legacy_id"`          // 传统ID free
			LegacyDiscount    bool   `json:"legacy_discount"`    // 传统折扣 false
			ExternallyManaged bool   `json:"externally_managed"` // 是否外部管理 false
		} `json:"plan"`
	} `json:"result"`
	ResultInfo struct {
		Page       int `json:"page"`        // 当前页码 1
		PerPage    int `json:"per_page"`    // 每页数量 20
		TotalPages int `json:"total_pages"` // 总页数 1
		Count      int `json:"count"`       // 当前页数量 1
		TotalCount int `json:"total_count"` // 总数量 1
	} `json:"result_info"`
	Success  bool          `json:"success"`  // 是否成功 true
	Errors   []interface{} `json:"errors"`   // 错误信息 []
	Messages []interface{} `json:"messages"` // 消息信息 []
}

// 列出区域列表
func (receiver *Client) ZoneList(pageSize, pageIndex int) (Zones, error) {
	// curl "https://api.cloudflare.com/client/v4/zones?account.id=$AccountId&per_page=100&page=2" \
	// -H "Authorization: Bearer $ApiToken"

	url := fmt.Sprintf("https://api.cloudflare.com/client/v4/zones?account.id=%s&per_page=%d&page=%d", receiver.AccountId, pageSize, pageIndex)
	resultJson, _, _, err := http.RequestProxyConfigure("GET", url, map[string]any{"Authorization": receiver.ApiToken}, nil, "application/json", 2000)

	var zones Zones
	snc.Unmarshal([]byte(resultJson), &zones)
	return zones, err
}
